= CSS: Float

== Problem

=== Problem

[.fragmnet]
Периодические возникает потребность в том, что бы одни элементы документа "обтекали" другие

== CSS property: `float`

=== `float`

[.step]
* Элемент является плавающим.
* Элементы идущие в коде после него, обтекают его
* Может применяться к любому элементу

=== `float`

|===
|value|content
|`left`|плавающий, прижат влево
|`right`|плавающий, прижат вправо
|`none`|обычный, не плавающий
|===


=== `float`

[.step]
* Если после `float` элемента следует еще один `float` элемент, второй `float` обтекает первый
* Если несколько `float` и один по размерам больше другого, то образуется область «не обтекания»
* Если несколько `float` не умещаются в ширину, то элементы переносятся ниже, при этом обтекая предыдущие

== CSS property: `clear`

=== `clear`

[.step]
* Запрещает данному элементу обтекать плавающие элементы, с одной или двух сторон
* Может применяться к любому элементу

=== `clear`

|===
|value|content
|`left`|не может обтекать плавающий элемент, который расположен слева
|`right`|не может обтекать плавающий элемент, который расположен справа
|`both`|не может обтекать плавающий элемент вообще
|`none`|может обтекать плавающие с любой стороны
|===

=== `clear`

[.step]
* Если отключено обтекание, то он не обтекает плавающие независимо от уровня вложенности
* Если отключено обтекание, то он не обтекает другие элементы, но это не мешает другим обтекать его
* Обтекаемым может быть любой элемент. Для обтекаемых блочных элементов важно указать ширину

== CSS property: `overflow`

=== `overflow`

[.step]
* Размер обтекающего элемента включает в себя площадь, закрытую плавающим элементами
* Фон, рамки обтекаемого распространяются на площадь закрытую плавающим
* Можно скрыть те части фона и рамок, закрытые плавающим

=== `overflow`

|===
|value|content
|`hidden`|скрыть части обтекаемого, которые закрыты плавающим
|===

=== `overflow`

[.step]
* Внешние поля и внутренние отступы обтекающих элементов нахлестываются на плавающие элементы, насколько это возможно
