= Internationalization and Localization

== Localization (l10n)

=== Localization (l10n)

[.step]
* Адаптация содержания программы к языковым соответствиям, культурным и другим требованиям определённого целевого рынка
* Включает перевод пользовательского интерфейса, а также адаптацию форматов цифр, дат и времени, денежных единиц, символов, графических изображений и т.д.
* Краткое название: *l10n*

== Internationalization (i18n)

=== Internationalization (i18n)

[.step]
* Создание программы таким образом, чтобы позволить для различных целевых рынков легко проводить *l10n*
* Возможные приёмы:
[.step]
** создание возможности применения Unicode, кодовой поддержки местных (локальных) языковых особенностей, форматов, календарей, форм обращения
** выделение локализированных элементов из кода, чтобы их можно было удобно менять и добавлять
* Сама локализация при этом может не производиться
* Краткое название: *i18n*

== i18n in Java

=== Класс `Locale`

[.step]
* Класс, хранящий данные о местности
* Содержит в себе информацию о языке и стране
* Используется для конфигурации системы
* Переключение языка в терминах java - это переключение локали
* Есть набор предустановленных локалей, но можно создавать и свои
* Для установки текущей локали: `Locale.setDefault(Locale.CHINESE);`

=== Класс `ResourceBundle`

[.step]
* *Bundle* == "Связка"
* Набор файлов, предназначенный для хранения переводов текста приложения на различных языки
* Каждый файл привязан к конкретной локали
* Также существует класс `ResourceBundle`, необходимый для чтения данных из этих файлов

== i18n in Jakarta EE

=== i18n with JSTL

* Для работы с механизмом интернационализации JSTL необходимо подключить к странице библиотеку `fmt`:

[source,jsp]
----
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %> 
----

=== Set language

Установка текущей локали:

[source,jsp]
----
<fmt:setLocale value="en_US"/>
<fmt:setLocale value="${sessionScope.language}"/>
----

Установка бандла (набора `.properties`-файлов с переводами)

[source,jsp]
----
<fmt:setBundle basename="translations" var="myBundle"/>
----

=== How use it?

[source,jsp]
----
<fmt:message key="login.username" bundle="${currentBundle}"/>
<fmt:message key="login.password" bundle="${currentBundle}"/>
<fmt:message key="login.submit" bundle="${currentBundle}"/>
----

=== What contains Bundle?

`translations_en_US.properties`:

[source,property]
----
login.username=Username
login.password=Password
login.submit=Submit
----

`translations_by_BY.properties`:

[source,property]
----
login.username=Імя карыстальніка
login.password=Пароль
login.submit=Увайсці
----
